### ISSUE TITLE
underflow

### ISSUE THREAD

**Issue by CinnamonDanish** [fatiherikli/brainfuck-visualizer#36]
subtracting from zero gives 255

in other words, fix your underflow error

**Comment by rdebath** [comment]
What do you expect the answer to be ?

**Comment by CinnamonDanish** [comment]
either keep 0 or terminate program. Or keep the wrapping behavior.
C and C++ both wrap, so it's fine, but underflow can cause big problems if you aren't expecting it / don't want all of your memory crashing. (i.e. iphone underflow 1970 glitch)

the best option would be have an option to select the behavior you want.
-cheers

**Comment by rdebath** [comment]
Ah, so is this actually a request to support the less common cell wrapping behaviours in brainfuck interpreters then? The normal display would be an unsigned byte as it is now, using a two-complement signed byte is also quite common (but has problems caused by some C compilers). The next likely cell type is a 32bit integer (unsigned or twos complement) as that is by far the commonest default integer in programming languages on current machines. The last of the moderately common cell sizes is unbounded integers, ones that go to (at least) several thousand bits in size and probably error on over/underflow if they get there.

The only byte-wide interpreter, I know, that normally errors on overflow or underflow is described by the author as "The fascist, score-computing interpreter used for BFCC". Also I have written one that counts the times when the fact of a cell wrapping changes the final result; which is NOT the same thing.

The "saturation" behaviour were you "get stuck" at the over/underflow limit occasionally exists as an option for an interpreter, but it's usually regarded as a bug (by the author) if it's the default behaviour. (Saturation on overflow is generally only useful for floating point values in image processing applications; other much prefer having Infinities and NaNs.)

Using a floating point value for a brainfuck interpreter doesn't work; it either simulates the previous mentioned saturation behaviour or acts really weirdly (depending on the amount of optimisation).

BTW: The 1970 glitch was due to an application taking zero time as always meaning there isn't a time. The Unix timestamp that Apple uses is actually a signed value so valid times go back to around 1902 Of course there are issues with locations (like Russia) that made the Gregorian adjustment in the twentieth century.

**Comment by CinnamonDanish** [comment]
Thank you for the verbosity, (no seriously, it's great) I think the option for non underflowing is still _vaguely_ important, i.e. if you had a section of program that behaved like so: (+[--]) you could have the program exit the loop rather than go from 1 -> 255. Yes most programming languages work better with NaNs and infinites, but brainfuck is so simple having a floor would be wonderful.

PS: I was completely off on the iPhone thing then! (I thought it was rolling from 0 to 18,446,744,073 709,551,615 because the phone was doing some check or another and ending up with a date before 1970, thus making a REALLY BIG (that's a scientific term) number and breaking when it comes up with a date that's 15 times longer than the expected lifespan of the universe.)

-Cheers

**Comment by rdebath** [comment]
Another way of making sure that sort of loop exits is to make the cell size prime. To make a loop of the style `+[--]` loop forever with a cell size of 257 rather than 256 needs a multiple of 257 minuses in the loop.

**Comment by CinnamonDanish** [comment]
that works (kinda) but then you no longer work in the wonderful world of 2^8.

I say kinda, because then the loop `++[---]` runs to R1 R0, so it takes two loops around to reach zero. this means if you had more complex loops, sure they would _eventually_ reach zero, but if you expect to get one 1 repetition out of your loop rather than 514, you are going to be a sad cookie.

-Cheers

**Comment by rdebath** [comment]
``` bf
++[-[->]-[---<]>]>>+++.>>>>>+.>--..<<+.>>-.++.-.[<]>>+.>>>>.>>.<.>+++++.<-.
```

**Comment by CinnamonDanish** [comment]
thanks?
```
>>>>>>>>--------<<<<<<<<
++++++++++++
[
[>++++ ++++]
<<<<<<<<-
>>>>>>>>--------<<<<<<<<
]
>++++ +++++ +++++ ++++.
>++++.
>+++++.
>++.
>+.
>++++ +++++ +++++ +++++ +.
>++++ ++++.
```
Very much longer, but fewer bits used. (plus I am much newer than you at this).

-Cheers
